imports:
    - { resource: tables.yml }

services:
    forumhulp.statistics.listener:
        class: forumhulp\statistics\event\listener
        arguments:
            - '@config'
            - '@request'
            - '@user'
            - '@dbal.conn'
            - '@template'
            - '@cache.driver'
            - '@service_container'
            - '%tables.online_table%'
            - '%tables.config_table%'
            - '%tables.se_table%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
    forumhulp.cron.statistics:
        class: forumhulp\statistics\cron\task\core\prune_statistics
        arguments:
            - '@config'
            - '@user'
            - '@dbal.conn'
            - '@log'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.online_table%'
            - '%tables.config_table%'
            - '%tables.archive_table%'
            - '%tables.stats_table%'
        calls:
            - [set_name, [forumhulp.cron.statistics]]
        tags:
            - { name: cron.task }
    forumhulp.statistics.acp.statistics_module:
        class: forumhulp\statistics\acp\statistics_module
        arguments:
            - '@user'
            - '@ext.manager'
            - '%core.root_path%'
